import Head from "next/head";

const Layout = props => {
  return (
    <>
      <Head>
        <title>Conference App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {props.children}
      </main>
    </>
  );
};

export default Layout;